services:
  mongo:
    build:
      context: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file: 
      - .env

  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017

  model:
    build:
      context: ./model
    depends_on:
      - fastapi

  kafka-spark:
    build:
      context: ./kafka-spark
    depends_on:
      - mongo

volumes:
  mongo_data: