services:
  mongo:
    build:
      context: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file: 
      - .env

  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
    depends_on:
      - kafka

  model:
    build:
      context: ./model
    depends_on:
      - fastapi

  pipeline:
    build:
      context: ./pipeline
    depends_on:
      - mongo
    environment:
      KAFKA_BROKER_URL: kafka:9092

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    ports:
      - "9092:9092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
    depends_on:
      - zookeeper

  zookeeper:
    image: bitnami/zookeeper:3.9.0
    ports:
      - "2181:2181"
    environment:
      environment:
      ALLOW_ANONYMOUS_LOGIN: "yes"
      ZOOKEEPER_CLIENT_PORT: 2181

volumes:
  mongo_data: