services:
  mongo:
    build:
      context: ./mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    env_file: 
      - .env

  fastapi:
    build:
      context: ./fastapi
    ports:
      - "8000:8000"
    depends_on:
      - kafka

  model:
    build:
      context: ./model
    depends_on:
      - fastapi

  kafka-spark:
    build:
      context: ./kafka-spark
    depends_on:
      - mongo
    
    zookeeper:
    image: wurstmeister/zookeeper:3.4.6
    ports:
      - "2181:2181"

  kafka:
    image: wurstmeister/kafka:2.12-2.2.1
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  mongo_data: