name: Docker Images

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Build the api/model dockerfile
      run: docker build ./model --file Dockerfile --tag my-image-name:$(date +%s)

    - uses: actions/checkout@v4
    - name: Build the front image
      run: docker build ./front --file Dockerfile --tag my-image-name:$(date +%s)

    - uses: actions/checkout@v4
    - name: Build the dataretrieval image
      run: docker build ./pipeline/data_retrieval --file Dockerfile --tag my-image-name:$(date +%s)

    - uses: actions/checkout@v4
    - name: Build the dataformatting image
      run: docker build ./pipeline/data_formatting --file Dockerfile --tag my-image-name:$(date +%s)
